name: gate_app
description: Gate - دسترسی آزاد با جیمیل
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_sign_in: ^6.2.1
  webview_flutter: ^4.8.0
  http: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
