name: Termux SSH

on:
  workflow_dispatch:

jobs:
  ssh:
    runs-on: ubuntu-latest
    timeout-minutes: 360

    steps:
      - name: Install Tmate
        run: |
          sudo apt update
          sudo apt install -y tmate

      - name: Start SSH Session
        run: |
          tmate -F &
          sleep 10

          echo ""
          echo "=============================="
          echo "SSH Command:"
          tmate display -p '#{tmate_ssh}'
          echo ""
          echo "Web Terminal:"
          tmate display -p '#{tmate_web}'
          echo "=============================="

          while true; do
            sleep 60
          done
